### ISSUE TITLE
可以支持1.19.2吗？

### ISSUE THREAD

**Issue by Dr-WeiAL** [Nova-Committee/LightEconomy#1]
1.19.2算是比较常用的版本了，可以加一个1.19.2版本吗(

**Comment by acaeaeeda** [comment]
+1

**Comment by Dr-WeiAL** [comment]
现在已经是1.20.1的时代力，建议一步到位直接1.20.1(

**Comment by VulpesStella** [comment]
> 现在已经是1.20.1的时代力，建议一步到位直接1.20.1(

好

**Comment by VulpesStella** [comment]
> > 现在已经是1.20.1的时代力，建议一步到位直接1.20.1(
> 
> 好

才发现当时没找重生要百科的开发组权限，我先传这了
[解压后使用.zip](https://github.com/Nova-Committee/LightEconomy/files/13546088/default.zip)
